# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "raspberrypi-custom"
BBFILE_PATTERN_raspberrypi-custom = "^${LAYERDIR}/"
BBFILE_PRIORITY_raspberrypi-custom = "9"

LAYERDEPENDS_raspberrypi-custom = "core raspberrypi"
LAYERSERIES_COMPAT_raspberrypi-custom = "nanbield scarthgap"

INHERIT:remove = "create-spdx"
